#!/bin/sh
# =============================================================================
# Remove dial-up from OpenWrt router via SSH
# Usage: ./remove.sh [user@host]    (default: root@192.168.1.1)
#
# Removes: bot binary, olcrtc binary, init script, sing-box tproxy routing
# rules (UCI network/firewall + nft snippet + config files), and the LuCI app.
#
# IMPORTANT: sing-box config files (config.json, whitelist.json, tproxy.nft)
# are deleted ONLY if their sha256 matches the repo version. A user-customized
# configuration is never clobbered.
# =============================================================================

set -e

HOST="${1:-root@192.168.1.1}"
REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
SSH_OPTS="-o LogLevel=ERROR -o ConnectTimeout=5 -o StrictHostKeyChecking=no"

ROUTER_BIN="/usr/bin/dial-up"
ROUTER_INIT="/etc/init.d/dial-up"
ROUTER_ENV="/etc/dial-up.env"
ROUTER_OLCRTC="/etc/olcrtc-linux-arm64"

GREEN='\033[32m'
RED='\033[31m'
YELLOW='\033[33m'
NC='\033[0m'

info()  { printf "${GREEN}[OK]${NC} %s\n" "$*"; }
warn()  { printf "${YELLOW}[!!]${NC} %s\n" "$*"; }
error() { printf "${RED}[ERR]${NC} %s\n" "$*"; exit 1; }

# sha256 of a local file (macOS shasum / linux sha256sum)
local_sha() {
    sha256sum "$1" 2>/dev/null | awk '{print $1}' || shasum -a 256 "$1" 2>/dev/null | awk '{print $1}'
}

# sha256 of a file on the router (busybox sha256sum / shasum)
remote_sha() {
    ssh $SSH_OPTS "$HOST" "sha256sum \"$1\" 2>/dev/null | awk '{print \$1}' || shasum -a 256 \"$1\" 2>/dev/null | awk '{print \$1}'"
}

# Remove remote file only if it matches the local reference file (sha256).
# Returns 0 (match+removed), 1 (differ/missing/skipped).
remove_if_match() {
    local desc="$1" local_file="$2" remote_path="$3"
    if [ ! -f "$local_file" ]; then
        warn "$desc: local reference missing, kept"
        return 1
    fi
    local L R
    L=$(local_sha "$local_file")
    R=$(remote_sha "$remote_path")
    if [ -z "$R" ]; then
        info "$desc: not present on router"
        return 1
    fi
    if [ "$L" = "$R" ]; then
        ssh $SSH_OPTS "$HOST" "rm -f \"$remote_path\""
        info "$desc: removed (matched repo version)"
        return 0
    fi
    warn "$desc: differs from repo version, kept"
}

echo ""
echo "╔══════════════════════════════════════╗"
echo "║   Remove dial-up!                    ║"
echo "║   Target: ${HOST}"
echo "╚══════════════════════════════════════╝"
echo ""

# ── Pre-flight ─────────────────────────────────────────────
info "Checking SSH connectivity..."
ssh $SSH_OPTS "$HOST" "command -v uci >/dev/null" 2>/dev/null || \
    error "SSH unreachable or not OpenWRT"

# ── Stop & disable service ─────────────────────────────────
info "Stopping and disabling service..."
ssh $SSH_OPTS "$HOST" "$ROUTER_INIT stop 2>/dev/null; $ROUTER_INIT disable 2>/dev/null; exit 0" || true
info "Service stopped and disabled"

# ── Remove binaries ────────────────────────────────────────
info "Removing binary..."
ssh $SSH_OPTS "$HOST" "rm -f $ROUTER_BIN" || true
info "Removing olcrtc binary..."
ssh $SSH_OPTS "$HOST" "rm -f $ROUTER_OLCRTC" || true

info "Removing init script..."
ssh $SSH_OPTS "$HOST" "rm -f $ROUTER_INIT" || true

# ── Remove sing-box config (only matched files) ────────────
# Each file is compared (sha256) against the repo version and deleted only on
# exact match. The tproxy.nft is generated by setup-singbox-tproxy.sh (heredoc),
# so we extract it to compare. UCI routing rules are removed only if tproxy.nft
# matched — that is the marker that this deployment owns the tproxy setup.
info "Checking sing-box config files against repo versions..."

TPROXY_OURS=0

remove_if_match "sing-box config.json"    "$REPO_DIR/deploy/openwrt/sing-box-config.json" "/etc/sing-box/config.json"
remove_if_match "sing-box whitelist.json" "$REPO_DIR/deploy/openwrt/whitelist.json"        "/etc/sing-box/whitelist.json"

# Extract the tproxy.nft body from setup-singbox-tproxy.sh (the only heredoc).
TPROXY_NFT_TMP=$(mktemp)
awk "/tproxy\.nft <<.EOF./{f=1;next} /^EOF\$/{f=0} f" \
    "$REPO_DIR/deploy/openwrt/setup-singbox-tproxy.sh" > "$TPROXY_NFT_TMP" 2>/dev/null
if remove_if_match "tproxy.nft" "$TPROXY_NFT_TMP" "/etc/sing-box/tproxy.nft"; then
    TPROXY_OURS=1
fi
rm -f "$TPROXY_NFT_TMP"

# Remove /etc/sing-box dir only if empty (never removes a dir with other files).
ssh $SSH_OPTS "$HOST" "rmdir /etc/sing-box 2>/dev/null; exit 0" || true

if [ "$TPROXY_OURS" = "1" ]; then
    info "Removing sing-box tproxy routing rules (UCI)..."
    ssh $SSH_OPTS "$HOST" "\
uci -q delete firewall.singbox_tproxy; \
uci -q delete network.tproxy_rule; \
uci -q delete network.tproxy_local; \
uci commit firewall; \
uci commit network; \
fw4 reload 2>/dev/null; \
exit 0" || warn "tproxy UCI cleanup partially failed"
    info "tproxy routing rules removed"
else
    warn "tproxy.nft not matched — keeping UCI routing rules (may be customized)"
fi

# ── Remove LuCI app ────────────────────────────────────────
info "Removing LuCI olcRTC app..."
ssh $SSH_OPTS "$HOST" "\
rm -f /usr/libexec/rpcd/olcrtc-bot \
      /usr/share/rpcd/acl.d/luci-app-olcrtc.json \
      /usr/share/luci/menu.d/luci-app-olcrtc.json; \
rm -rf /www/luci-static/resources/view/olcrtc; \
/etc/init.d/rpcd restart 2>/dev/null; \
exit 0" || warn "LuCI cleanup partially failed"
info "LuCI app removed"

ENV_EXISTS=$(ssh $SSH_OPTS "$HOST" "[ -f $ROUTER_ENV ] && echo yes || echo no")
if [ "$ENV_EXISTS" = "yes" ]; then
    warn "Env file $ROUTER_ENV preserved (delete manually: ssh $HOST rm $ROUTER_ENV)"
fi

# ══════════════════════════════════════════════════════════
# VERIFICATION
# ══════════════════════════════════════════════════════════
echo ""
echo "── Verification ──────────────────────────"
echo ""

FAIL=0

check() {
    local desc="$1" cmd="$2"
    if ssh $SSH_OPTS "$HOST" "$cmd" >/dev/null 2>&1; then
        info "$desc"
    else
        printf "${RED}[ERR]${NC} %s\n" "$desc (still present)"
        FAIL=1
    fi
}

check "Binary removed"        "[ ! -f '$ROUTER_BIN' ]"
check "OlcRTC binary removed" "[ ! -f '$ROUTER_OLCRTC' ]"
check "Init removed"          "[ ! -f '$ROUTER_INIT' ]"
check "Init disabled"         "! find /etc/rc.d -name '*olcrtc*' 2>/dev/null | grep -q ."
check "LuCI menu removed"     "[ ! -f /usr/share/luci/menu.d/luci-app-olcrtc.json ]"
check "rpcd backend removed"  "[ ! -f /usr/libexec/rpcd/olcrtc-bot ]"
check "LuCI views removed"    "[ ! -d /www/luci-static/resources/view/olcrtc ]"

# tproxy checks only apply when we owned the tproxy deployment.
if [ "$TPROXY_OURS" = "1" ]; then
    check "tproxy fw include removed"  "! uci -q get firewall.singbox_tproxy.path >/dev/null 2>&1"
    check "tproxy net rule removed"    "! uci -q get network.tproxy_rule.mark >/dev/null 2>&1"
    check "tproxy nft snippet removed" "[ ! -f /etc/sing-box/tproxy.nft ]"
else
    info "tproxy rules kept (config customized or absent)"
fi

echo ""
if [ "$FAIL" = "0" ]; then
    printf "${GREEN}╔══════════════════════════════════════╗${NC}\n"
    printf "${GREEN}║  Removal complete!                   ║${NC}\n"
    printf "${GREEN}╚══════════════════════════════════════╝${NC}\n"
else
    exit 1
fi
echo ""
